language: python

sudo: false

python:
  - "3.5"

env:
  global:
    - WAIT_FOR_ES=1

install:
  - pip install git+https://github.com/elastic/elasticsearch-py.git#egg=elasticsearch
  - pip install .

script:
  - python setup.py test

notifications:
  email:
    recipients:
      - honza.kral@gmail.com
